### ISSUE TITLE
Error in admin section

### ISSUE THREAD

**Issue by 29sunil** [husseycoding/ajaxcartpopup#55]
We get below error after install this extension
Fatal error: Uncaught Error: Class 'HusseyCoding_AjaxCartPopup_Helper_Data' not found in /home/mhzf51ttt0er/public_html/app/Mage.php:547 Stack trace: #0 /home/mhzf51ttt0er/public_html/includes/src/Mage_Adminhtml_Block_System_Config_Tabs.php(117): Mage::helper('ajaxcartpopup') #1 /home/mhzf51ttt0er/public_html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(104): Mage_Adminhtml_Block_System_Config_Tabs->initTabs() #2 /home/mhzf51ttt0er/public_html/includes/src/__default.php(14334): Mage_Adminhtml_System_ConfigController->editAction() #3 /home/mhzf51ttt0er/public_html/includes/src/__default.php(18813): Mage_Core_Controller_Varien_Action->dispatch('edit') #4 /home/mhzf51ttt0er/public_html/includes/src/__default.php(18343): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) #5 /home/mhzf51ttt0er/public_html/includes/src/__default.php(21279): Mage_Core_Controller_Varien_Front->dispatch() #6 /home/mhzf51ttt0er/public_html/app/Mage.php(683): Mage_Core_Model_App->run in /home/mhzf51ttt0er/public_html/app/Mage.php on line 547

**Comment by husseycoding** [comment]
Unfortunately we aren't offering support for this free extension anymore - it hasn't been maintained for some time.  Feel free to modify as required, but all I can say is the last time this was worked on no error like that was showing.
